# Generated by Django 3.0.5 on 2022-04-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='photo',
        ),
    ]
