# Generated by Django 3.0.5 on 2022-04-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_myuser_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='title',
        ),
    ]
