# Generated by Django 3.0.5 on 2022-04-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220405_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(default='Raj', max_length=200),
        ),
    ]
