# Generated by Django 3.0.5 on 2022-04-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myuser_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='time',
            field=models.DateTimeField(default='Raj'),
        ),
    ]
