# Generated by Django 3.0.5 on 2022-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220405_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='time',
        ),
        migrations.AddField(
            model_name='myuser',
            name='pub_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
