# Generated by Django 3.0.5 on 2022-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220405_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
