# Generated by Django 3.0.5 on 2022-04-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220405_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='pub_date',
        ),
    ]
