# Generated by Django 3.0.5 on 2022-04-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_myuser_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.TextField(default='', max_length=900),
        ),
    ]
